package io.inprice.scrapper.api.config;

public enum PropName {
	APP_PORT,	
	APP_RUNNING_AT,	
	APP_PROD_UNIQUENESS,
	APP_LINK_UNIQUENESS,
	APP_SHOWING_SQL_QUERIES,
	APP_WAITING_TIME,

	DB_DRIVER,
	DB_HOST,
	DB_PORT,
	DB_USERNAME,
	DB_PASSWORD,
	DB_DATABASE,
	DB_ADDITIONS,
	
	MQ_HOST,
	MQ_PORT,
	MQ_USERNAME,
	MQ_PASSWORD,

	MQ_EXCHANGE_CHANGES,
	MQ_ROUTING_DELETED_LINKS,

	REDIS_HOST,
	REDIS_PORT,
	REDIS_PASSWORD,

	TTL_ACCESS_TOKENS,
	TTL_REFRESH_TOKENS,
	
	OTHER_FRONTEND_BASE_URL,
	OTHER_SENDER_EMAIL,

	PREFIX_FOR_SEARCH_EBAY,
	PREFIX_FOR_SEARCH_AMAZON,
	
	API_KEY_SENDGRID,
	SECURITY_SALT_ROUNDS
}
